apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: simple-200-return
spec:
  args:
  - name: service-name
  metrics:
  - name: verify-canary
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
                - name: simple-http-call
                  image: curlimages/curl:8.12.1
                  command:
                    ["curl",  "--silent", "rollout-canary-preview/callme"]
              restartPolicy: Never