---
apiVersion: v1
kind: Service
metadata:
  name: rollout-canary-active
  labels:
    app: summer-k8s-app  
spec:
  type: NodePort
  selector:
    app: summer-k8s-app
  ports:
      - nodePort: 31000
        protocol: TCP
        port: 8080
       